### ISSUE TITLE
Multiple NIC support?

### ISSUE THREAD

**Issue by karldd** [diversario/node-ssdp#34]
I've been using node-ssdp 2.2.1 as a client on Windows 8.1 and it has been working perfectly, thanks!

Recently I installed on another Windows 8.1 machine and found that everything went silent. I unfortunately don't have full-time access to that machine, but I did notice it has two network cards returned by `os.networkInterfaces()` as:

```
"network_interfaces": {
            "Ethernet": [
              {
                "family": "IPv6", 
                "netmask": "ffff:ffff:ffff:ffff::", 
                "mac": "xx:xx:xx:xx:xx:xx", 
                "internal": false, 
                "scopeid": 3, 
                "address": "fe80::c570:b450:f38c:e02b"
              }, 
              {
                "mac": "xx:xx:xx:xx:xx:xx", 
                "internal": false, 
                "netmask": "255.255.255.0", 
                "family": "IPv4", 
                "address": "10.10.20.1"
              }
            ], 
            "Ethernet_2": [
              {
                "family": "IPv6", 
                "netmask": "ffff:ffff:ffff:ffff::", 
                "mac": "yy:yy:yy:yy:yy:yy", 
                "internal": false, 
                "scopeid": 4, 
                "address": "fe80::9864:ed9b:ea63:6506"
              }, 
              {
                "mac": "yy:yy:yy:yy:yy:yy", 
                "internal": false, 
                "netmask": "255.255.255.0", 
                "family": "IPv4", 
                "address": "192.168.35.54"
              }
            ], 
            "Loopback_Pseudo-Interface_1": [
              {
                "family": "IPv6", 
                "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff", 
                "mac": "00:00:00:00:00:00", 
                "internal": true, 
                "scopeid": 0, 
                "address": "::1"
              }, 
              {
                "mac": "00:00:00:00:00:00", 
                "internal": true, 
                "netmask": "255.0.0.0", 
                "family": "IPv4", 
                "address": "127.0.0.1"
              }
            ]
          }
```

Here `Ethernet` is connected to a single machine using `10.10.20.1`, while `Ethernet_2` is connected to the wider internal network via `192.168.35.54`. I'm wondering how node-ssdp behaves in this scenario?

I noticed a similar issue [here](https://github.com/jishi/node-sonos-http-api/issues/3), and it looks like the [relevant code](https://github.com/jishi/node-sonos-discovery/blob/master/lib/sonos.js#L134) actually creates a socket for each host IP address it finds.

I'm wondering if the simple solution is to create a `new Client()` for each IP address? Or if this scenario should be handled at a lower level? Thoughts?

Thanks!

**Comment by diversario** [comment]
I haven't ran into this issue myself so I can't speak from experience but I suppose that if the module you linked solved the same issue it could apply in this case as well. I'm going to look into that. Going to be a bit difficult to test, though. Would you be able to test a branch if I push one up?

**Comment by karldd** [comment]
Absolutely, I have periodic access to two machines that I can replicate the problem with. Anything in the short term you'd like to try?

**Comment by diversario** [comment]
I don't think there's anything; I'm working on this now, ran into an issue where server doesn't seem to receive multicast messages when bound to an address from `os.networkInterfaces()`. Binding to `0.0.0.0` (as it does currently) works. Might take some time to figure it out.

**Comment by karldd** [comment]
I tried this on another computer that has a similar dual NIC configuration today and it worked as expected. I noticed that the `os.networkInterfaces()` order was reversed, with the internet connected NIC coming first and the local NIC second:

```js
"network_interfaces": {
  "Local_Area_Connection_2": [
    {
      "family": "IPv6",
      "netmask": "ffff:ffff:ffff:ffff::",
      "mac": "XX:XX:XX:XX:XX:XX",
      "internal": false,
      "scopeid": 14,
      "address": "fe80::2450:9825:159e:dd61"
    },
    {
      "mac": "XX:XX:XX:XX:XX:XX",
      "internal": false,
      "netmask": "255.255.255.0",
      "family": "IPv4",
      "address": "192.168.35.180"
    }
  ],
  "Local_Area_Connection": [
    {
      "family": "IPv6",
      "netmask": "ffff:ffff:ffff:ffff::",
      "mac": "XX:XX:XX:XX:XX:XX",
      "internal": false,
      "scopeid": 11,
      "address": "fe80::2065:45d4:1590:2af9"
    },
    {
      "mac": "XX:XX:XX:XX:XX:XX",
      "internal": false,
      "netmask": "255.255.255.0",
      "family": "IPv4",
      "address": "10.10.20.1"
    }
  ],
  "Loopback_Pseudo-Interface_1": [
    {
      "family": "IPv6",
      "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      "mac": "00:00:00:00:00:00",
      "internal": true,
      "scopeid": 0,
      "address": "::1"
    },
    {
      "mac": "00:00:00:00:00:00",
      "internal": true,
      "netmask": "255.0.0.0",
      "family": "IPv4",
      "address": "127.0.0.1"
    }
  ]
}
```

This seems to confirm the theory that it is the NIC order affecting things.

**Comment by diversario** [comment]
I'm not sure if automatically creating sockets for every single interface is a good idea because user will have no control over which interface to use. I can see how it can be convenient but at the same time potentially problematic. What do you think?
I do think that a separate client per interface is a simple workaround for this (have you tried it?). Might be better to go with that rather than using all interfaces automatically.

**Comment by karldd** [comment]
I haven't tried the separate client per interface but can do later in the week. Will report back.

**Comment by karldd** [comment]
Iterating over each NIC and creating a client with the `unicastHost` option set, only generates responses for a single NIC, the second one remains silent. Using the following [code](https://gist.github.com/karldd/ea07732b4601d1028952) I get this output:

```
[192.168.35.54] SSDP search started
[10.10.20.1] SSDP search started
[10.10.20.1] SSDP device found: uuid:6e1ba960-c47f-463b-8b9e-3ec54265e1a5, http:
//10.10.20.2:2869/upnphost/udhisapi.dll?content=uuid:6e1ba960-c47f-463b-8b9e-3ec
54265e1a5
...
[10.10.20.1] SSDP device found: urn:Microsoft Windows Peer Name Resolution Proto
col: V4:IPV6:LinkLocal, 10.10.20.2
[192.168.35.54] SSDP timeout
[10.10.20.1] SSDP timeout
```

[192.168.35.54] is connected to the wider network, and [10.10.20.1] is a cross-over cable connection to a single machine:
```
> os.networkInterfaces()
{ 'Ethernet 2': 
   [ { address: 'fe80::9864:ed9b:ea63:6506',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'xx:xx:xx:xx:xx:xx',
       scopeid: 4,
       internal: false },
     { address: '192.168.35.54',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false } ],
  Ethernet:
   [ { address: 'fe80::c570:b450:f38c:e02b',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'xx:xx:xx:xx:xx:xx',
       scopeid: 3,
       internal: false },
     { address: '10.10.20.1',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false } ],
  'Loopback Pseudo-Interface 1':
   [ { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true },
     { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true } ] }
```
Whats surprising is that the NIC connected to the wider network [192.168.35.54] actually appears first in the list and yet somehow only the second NIC [10.10.20.1] gets responses.


On another machine with multiple NICs I got the following output, this time with the [192.168.35.180] NIC connected to the wider network getting responses and the cross-over cable machine [10.10.20.1] not getting any responses:

```
[192.168.35.180] SSDP search started
[10.10.20.1] SSDP search started
[192.168.35.180] SSDP device found: urn:Microsoft Windows Peer Name Resolution P
rotocol: V4:IPV6:LinkLocal, 192.168.35.164
...
[192.168.35.180] SSDP timeout
[10.10.20.1] SSDP timeout
```

NIC setup as follows:
```
> os.networkInterfaces()
{ 'Local Area Connection 2':
   [ { address: 'fe80::2450:9825:159e:dd61',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'xx:xx:xx:xx:xx:xx',
       scopeid: 14,
       internal: false },
     { address: '192.168.35.180',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false } ],
  'Local Area Connection':
   [ { address: 'fe80::2065:45d4:1590:2af9',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'xx:xx:xx:xx:xx:xx',
       scopeid: 11,
       internal: false },
     { address: '10.10.20.1',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false } ],
  'Loopback Pseudo-Interface 1':
   [ { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true },
     { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true } ] }
```

I also tried a single client that specified the `unicastHost` option and that saw the same result as the multiple client case each time. Likewise, not specifying the `unicastHost` option would only use one NIC. I'm not sure what the logic is to decide which NIC it uses.

Thoughts?

**Comment by ds82** [comment]
I can confirm this bug. Have multiple NICs. I create a client for each nic. I only get events on one (not the first one I registered though).

**Comment by diversario** [comment]
So, @karldd, what you see is you only able to get events from one NIC – no matter how you create the client, is that correct? Same for you, @ds82?

There is one thing that comes to mind – the multicast membership is currently added without specifying the interface on which to join the group; it works with one NIC because the OS will know which one to use but for multiple NICs – they might end up joining on a wrong interface.

**Comment by diversario** [comment]
Would one of you guys be able to run the `feature/i34-multiple-nic-support-test-branch` branch and see if that changes anything?

**Comment by ds82** [comment]
I may have to withdraw my bug report ... I had an active VPN connection on the interface that did not get any events. If I disconnect the VPN, I get events for both NICs (when creating a client for each NIC, what I think is ok). I think the VPN problem is by design and there's maybe nothing you could do about it, right?

**Comment by diversario** [comment]
Ah. Frankly, I don't know how VPN interferes with multicast, but I know for sure that I have weird issues on my machine with `cURL` when running VPN, so it's possible that multicast traffic gets affected as well.

**Comment by ds82** [comment]
I tested your branch.  Works well if I turn off the VPN (actually same behaviour like before).

**Comment by diversario** [comment]
Thanks, @ds82. So, at least it doesn't break it. I wonder if @karldd's setup includes VPN.

**Comment by karldd** [comment]
No VPN that I know of, but it isn't my personal machine so hard to say for sure. Hopefully I can test this tomorrow and report back.

**Comment by karldd** [comment]
So this doesn't look to make any difference. The behavior is quite odd.
For the one machine I tested here is what happens:

- When I don't define a `unicastHost` I get results from the `10.x.x.x` address.
- When I set the `unicastHost` to the `10.x.x.x` address I get *no* results.
- When I set the `unicastHost` to the `192.x.x.x` address I *do* get results.

**Comment by diversario** [comment]
It is weird. I'm gonna make a VM and try to test it out to see if I can spot an issue.

**Comment by karldd** [comment]
Thanks! Let me know if there is anything you want me to test out.

**Comment by etiktin** [comment]
I'm seeing the same issue when trying out the server example. I have multiple NICs (I have 3 more, but they are disabled): 
```
{ WiFi:
   [ { address: '12.0.0.42',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false } ],
  'VirtualBox Host-Only Network':
   [ { address: '192.168.56.1',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false } ],
  'Loopback Pseudo-Interface 1':
   [ { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true },
     { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true } ] }
```

Instead of sending `NOTIFY` through all of them (`WiFi` is my actual internet access), it tries to send it only through `VirtualBox Host-Only Network` which is connected to nothing (it's a fake NIC that virtual box creates when you install it). If I disable `VirtualBox Host-Only Network` and rerun the example, it starts sending the message using `WiFi`.
To test, if it's something in node, I tried to create an http server without providing a specific address (it defaults to 0.0.0.0 for IP4) and that worked well across all interfaces.

I'm using Windows 8.1 (64 bit) and `node-ssdp` v2.6.2.

**Comment by diversario** [comment]
The issue is probably with using a single socket (in the module itself). Since I'm calling `addMembership` with no interface as the second argument it binds to the interface of the OS choosing.

I was thinking that maybe user could specify the interface but that puts burden of dealing with interface discovery on the user and it's probably not what a typical user would want to do. So, I'm going to have to rewrite that part of the module to create and manage multiple sockets (which I tried to avoid but ¯\_(ツ)_/¯ ).

**Comment by etiktin** [comment]
> I was thinking that maybe user could specify the interface but that puts burden of dealing with interface discovery on the user and it's probably not what a typical user would want to do

It would be nice if we have both options, but yes most users will probably just use the default option.

> So, I'm going to have to rewrite that part of the module to create and manage multiple sockets

:+1:

**Comment by diversario** [comment]
Could someone with a working setup see if this 719526d makes a difference?

**Comment by Kotlarz** [comment]
@diversario I gave the branch a try, I have an additional interface (tun0) when the VPN is connected.

```
> os.networkInterfaces()
{ lo: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true } ],
  wlan0: 
   [ { address: '192.168.10.133',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'xx:xx:xx:xx:xx:xx',
       internal: false },
     { address: 'fe80::5627:1eff:feb6:5ac5',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'xx:xx:xx:xx:xx:xx',
       scopeid: 2,
       internal: false } ],
  tun0: 
   [ { address: '10.113.1.6',
       netmask: '255.255.255.255',
       family: 'IPv4',
       mac: '08:00:08:00:80:00',
       internal: false } ] }
```

tun0 information:

```
$ ip link show dev tun0
10: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
   link/none 
```

The branch works fine without the tunnel being active:

```
kotlarz@laptop  /tmp/node-ssdp   feature/i34-multiple-nic-support-attempt-3  node example/client.js
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":30,"msg":"discovering all IPs from interface lo","time":"2016-01-24T21:48:01.392Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":126},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":30,"msg":"discovering all IPs from interface wlan0","time":"2016-01-24T21:48:01.396Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":126},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":30,"msg":"Will use interface wlan0","time":"2016-01-24T21:48:01.397Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":130},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":30,"address":"http://0.0.0.0:1900","interface":"192.168.10.133","msg":"SSDP listening","time":"2016-01-24T21:48:01.403Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":199,"func":"onSocketListening"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":10,"msg":"Sending an M-SEARCH request","time":"2016-01-24T21:48:01.404Z","src":{"file":"/tmp/node-ssdp/lib/client.js","line":54,"func":"search"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":10,"message":"M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:ContentDirectory:1\r\nMAN: \"ssdp:discover\"\r\nMX: 3\r\n\r\n","msg":"Sent M-SEARCH request","time":"2016-01-24T21:48:01.405Z","src":{"file":"/tmp/node-ssdp/lib/client.js","line":59},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":10,"ST":"urn:schemas-upnp-org:service:ContentDirectory:1","address":"192.168.10.133","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:01.406Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11665,"level":30,"message":"HTTP/1.1 200 OK\r\nLocation: http://192.168.10.133:32469/DeviceDescription.xml\r\nCache-Control: max-age=1800\r\nServer: UPnP/1.0 DLNADOC/1.50 Platinum/1.0.4.11\r\nEXT: \r\nUSN: uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx::urn:schemas-upnp-org:service:ContentDirectory:1\r\nST: urn:schemas-upnp-org:service:ContentDirectory:1\r\nDate: Sun, 24 Jan 2016 21:48:02 GMT\r\n\r\n","msg":"SSDP response","time":"2016-01-24T21:48:02.407Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":394,"func":"parseResponse"},"v":0}
Got a response to an m-search:
200
{
  "LOCATION": "http://192.168.10.133:32469/DeviceDescription.xml",
  "CACHE-CONTROL": "max-age=1800",
  "SERVER": "UPnP/1.0 DLNADOC/1.50 Platinum/1.0.4.11",
  "EXT": "",
  "USN": "uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx::urn:schemas-upnp-org:service:ContentDirectory:1",
  "ST": "urn:schemas-upnp-org:service:ContentDirectory:1",
  "DATE": "Sun, 24 Jan 2016 21:48:02 GMT"
}
{
  "address": "192.168.10.133",
  "family": "IPv4",
  "port": 47794,
  "size": 352
}
```

But sadly does not work as expected with the VPN connected:

```
kotlarz@laptop  /tmp/node-ssdp   feature/i34-multiple-nic-support-attempt-3  node example/client.js
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"msg":"discovering all IPs from interface lo","time":"2016-01-24T21:48:28.781Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":126},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"msg":"discovering all IPs from interface wlan0","time":"2016-01-24T21:48:28.784Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":126},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"msg":"Will use interface wlan0","time":"2016-01-24T21:48:28.785Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":130},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"msg":"discovering all IPs from interface tun0","time":"2016-01-24T21:48:28.785Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":126},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"msg":"Will use interface tun0","time":"2016-01-24T21:48:28.785Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":130},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"address":"http://0.0.0.0:1900","interface":"192.168.10.133","msg":"SSDP listening","time":"2016-01-24T21:48:28.792Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":199,"func":"onSocketListening"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":30,"address":"http://0.0.0.0:1900","interface":"10.113.1.6","msg":"SSDP listening","time":"2016-01-24T21:48:28.793Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":199,"func":"onSocketListening"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"msg":"Sending an M-SEARCH request","time":"2016-01-24T21:48:28.793Z","src":{"file":"/tmp/node-ssdp/lib/client.js","line":54,"func":"search"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"message":"M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:ContentDirectory:1\r\nMAN: \"ssdp:discover\"\r\nMX: 3\r\n\r\n","msg":"Sent M-SEARCH request","time":"2016-01-24T21:48:28.795Z","src":{"file":"/tmp/node-ssdp/lib/client.js","line":59},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:schemas-upnp-org:service:ContentDirectory:1","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:28.796Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:schemas-upnp-org:service:ContentDirectory:1","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:28.797Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:schemas-upnp-org:service:ContentDirectory:1","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:28.797Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:schemas-upnp-org:service:ContentDirectory:1","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:28.797Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"10.113.1.6","port":58983,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:29.054Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"192.168.10.133","port":38122,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:29.055Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"10.113.1.6","port":58983,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:29.055Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"192.168.10.133","port":38122,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:29.056Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"10.113.1.6","port":58983,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:30.056Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"192.168.10.133","port":38122,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:30.056Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"10.113.1.6","port":58983,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:30.056Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"192.168.10.133","port":38122,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:30.057Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"10.113.1.6","port":58983,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:31.057Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"192.168.10.133","port":38122,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:31.058Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"10.113.1.6","port":58983,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:31.059Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"urn:dial-multiscreen-org:service:dial:1","address":"192.168.10.133","port":38122,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:31.060Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"ssdp:all","address":"10.113.1.6","port":51230,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.044Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"ssdp:all","address":"10.113.1.6","port":51230,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.045Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":42993,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.201Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":42993,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.202Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":42993,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.203Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":42993,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.203Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":54229,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.516Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":54229,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.516Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":54229,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.518Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"upnp:rootdevice","address":"10.113.1.6","port":54229,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:33.518Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"msg":"Sending an M-SEARCH request","time":"2016-01-24T21:48:38.793Z","src":{"file":"/tmp/node-ssdp/lib/client.js","line":54,"func":"search"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"message":"M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: ssdp:all\r\nMAN: \"ssdp:discover\"\r\nMX: 3\r\n\r\n","msg":"Sent M-SEARCH request","time":"2016-01-24T21:48:38.794Z","src":{"file":"/tmp/node-ssdp/lib/client.js","line":59},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"ssdp:all","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:38.794Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"ssdp:all","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:38.794Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"ssdp:all","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:38.795Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
{"name":"ssdp-client","hostname":"laptop","pid":11811,"level":10,"ST":"ssdp:all","address":"10.113.1.6","port":1900,"msg":"SSDP M-SEARCH event","time":"2016-01-24T21:48:38.795Z","src":{"file":"/tmp/node-ssdp/lib/index.js","line":307,"func":"SSDP._msearch"},"v":0}
...
```

**Comment by endoplasmic** [comment]
I can confirm that npm install https://github.com/diversario/node-ssdp#feature/i34-multiple-nic-support-attempt-3 works now (DEBUG=node-ssdp:server doesn't spit out any info, but that's alright for now)

My test environment is having a MacBook Pro with wifi connected and the thunderbolt to ethernet adapter connected. Before the feature branch it wouldn't work at all unless I was down to 1 interface. 

Seems to work ok now though, thanks so much for fixing it (well in my case anyways!)

**Comment by diversario** [comment]
@Kotlarz what breaks for you when you're connected to VPN?

@endoplasmic thank you very much for testing it out! This is progress. Now, I need to incorporate changes in master (`DEBUG=...` does not work because this branch was cut before the logging overhaul).

**Comment by endoplasmic** [comment]
@diversario right on, I'll keep an eye out here for when they roll into master and I can update my package.json :)

**Comment by diversario** [comment]
FYI, branch [feature/i34-multiple-nic-support-attempt-3](https://github.com/diversario/node-ssdp/compare/feature/i34-multiple-nic-support-attempt-3) is now up to date with `master`. I haven't had a chance to test it at all and especially in the conditions it supposed to address, so, if anyone wants to give it a try it would be fantastic 🙏

**Comment by almightyju** [comment]
Well I'm resurrecting this since I just ran into the same issue using this branch, I had to make a tiny change to make this work for me in lib/index.js:208 from
`socket.bind(self._ssdpPort, next) // socket binds on 0.0.0.0`
to
`socket.bind(self._ssdpPort, iface, next) // socket binds on 0.0.0.0`

I'm currently testing using a vmware machine so maybe theres something special making it need to bind to the specif ip address but it works for me :)

**Comment by diversario** [comment]
Interesting. So you have to bind explicitly in order for this to work? Kind of makes sense since otherwise they would all bind to `0.0.0.0`. In this system, how many NICs do you have, @almightyju ?

**Comment by diversario** [comment]
Ok, there's now `node-ssdp@3.0.0-beta1` on npm.

**Comment by almightyju** [comment]
It's strange but yes I have to bind explicitly to each NIC, I have 2 physical and 2 vmware NIC's

**Comment by almightyju** [comment]
Just updated to the beta and it's all working fab with the new option, thank you!

**Comment by diversario** [comment]
@endoplasmic care to try the v3 beta? :)

**Comment by garylesueur** [comment]
FYI neither the beta3 or attempt3 branch are working for me on multiple nics. Am on a Mac with wifi and ethernet connected with the nic service order set high up and the device for discovery is on the Wifi. Thanks.

**Comment by ds82** [comment]
For me, it actually works 👍  😁
I'm on a mac (10.10.5) with two ethernet connections and an active VPN connection.
Using ..
```
...
const client = new Client({explicitSocketBind: true});
...
```
..actually works! Well done! 😎

**Comment by colthreepv** [comment]
It doesn't seem to work for me.
I have many NIC(s) on the computer I am running this, it's a standard win10x64 install, firewall down (to exclude any issues with that) during the tests

I have edited `client.js` adding `explicitSocketBind: true`
![2016-12-19 11_25_15-](https://cloud.githubusercontent.com/assets/2657230/21309299/1981ca04-c5de-11e6-8c28-5bcba3dc8d4f.png)

NIC dump:
```
{
  "Ethernet 2": [
    {
      "address": "fe80::a956:9e97:c3df:948b",
      "netmask": "ffff:ffff:ffff:ffff::",
      "family": "IPv6",
      "mac": "0a:00:27:00:00:08",
      "scopeid": 8,
      "internal": false
    },
    {
      "address": "192.168.56.1",
      "netmask": "255.255.255.0",
      "family": "IPv4",
      "mac": "0a:00:27:00:00:08",
      "internal": false
    }
  ],
  "VirtualBox Host-Only Network #3": [
    {
      "address": "fe80::c087:cfa6:6581:5f9",
      "netmask": "ffff:ffff:ffff:ffff::",
      "family": "IPv6",
      "mac": "0a:00:27:00:00:0f",
      "scopeid": 15,
      "internal": false
    },
    {
      "address": "192.168.99.1",
      "netmask": "255.255.255.0",
      "family": "IPv4",
      "mac": "0a:00:27:00:00:0f",
      "internal": false
    }
  ],
  "VirtualBox Host-Only Network #4": [
    {
      "address": "fe80::9df5:9cf5:6f43:2ce5",
      "netmask": "ffff:ffff:ffff:ffff::",
      "family": "IPv6",
      "mac": "0a:00:27:00:00:0b",
      "scopeid": 11,
      "internal": false
    },
    {
      "address": "192.168.100.1",
      "netmask": "255.255.255.0",
      "family": "IPv4",
      "mac": "0a:00:27:00:00:0b",
      "internal": false
    }
  ],
  "Wi-Fi": [
    {
      "address": "fe80::2c9f:4019:a5ce:74cf",
      "netmask": "ffff:ffff:ffff:ffff::",
      "family": "IPv6",
      "mac": "6c:71:d9:78:b7:f0",
      "scopeid": 19,
      "internal": false
    },
    {
      "address": "10.15.7.33",
      "netmask": "255.255.248.0",
      "family": "IPv4",
      "mac": "6c:71:d9:78:b7:f0",
      "internal": false
    }
  ],
  "Loopback Pseudo-Interface 1": [
    {
      "address": "::1",
      "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      "family": "IPv6",
      "mac": "00:00:00:00:00:00",
      "scopeid": 0,
      "internal": true
    },
    {
      "address": "127.0.0.1",
      "netmask": "255.0.0.0",
      "family": "IPv4",
      "mac": "00:00:00:00:00:00",
      "internal": true
    }
  ]
}
```

**Comment by diversario** [comment]
Since it's working at least for some I'll promote beta2 to release.

Frankly, I'm puzzled as to what the problem could be.

It's possible that UDP TTL is set too low (by default, it's 1 and I'm going to bump it to a default of 4). You could try passing `ssdpTtl: 255` to the constructor to see if that makes any difference.

**Comment by monsur** [comment]
I am seeing a similar symptom as this bug, though I don't think it is due to multiple nics. I was able to narrow it down to something that changed between 2.7.1 and 2.7.2. When I run my script using node-ssdp 2.7.1, my script works. When I run using node-ssdp 2.7.2, it does not. My GitHub skills are not good enough to see what changed between those two releases.

**Comment by monsur** [comment]
Here's the diff between 2.7.1 and 2.7.2:

https://github.com/diversario/node-ssdp/compare/v2.7.1...v2.7.2

It looks like the issue is the change to lib/index.js:

https://github.com/diversario/node-ssdp/commit/149c6ea6e1bc0273ba4ebe552c1fb96f8f917eca#diff-6d186b954a58d5bb740f73d84fe39073

When I comment the unref() call, my script works again. I tried commenting out unref() in the lastest version 3.2.1, and my script works again. This may explain the issues others are seeing here.

**Comment by monsur** [comment]
Sorry for the spam. I finally figured out my issue, and its in my code. I was calling client.stop() a bit earlier than I should, which lead to my script prematurely ending. If anyone else stumbles across this issue, check where you are calling client.stop(). Here's how I fixed things in my code:

https://github.com/monsur/sonos-now-playing/commit/f4e93dad1593a83569aedacdc87d79a435e2b840

**Comment by epelc** [comment]
I found some info which might help in the future. The `explicitSocketBind` option fixes this on macOS 10.13.1 with two NICs(one with local wifi for ssdp and one WAN ethernet).

Basically if you do enable `explicitSocketBind` and you have multiple NICs, it will broadcast by sending out using the first NICs ip as the from address instead of broadcasting on both NICs separately.

Sending with `explicitSocketBind`
```
12:24:29.408088 IP (tos 0x0, ttl 4, id 27978, offset 0, flags [none], proto UDP (17), length 157, bad cksum 0 (->e0db)!)
    172.19.204.28.61876 > 239.255.255.250.1900: [bad udp cksum 0x68c5 -> 0xaab6!] UDP, length 129
..^...8..?y...E...mJ.................l..h.M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
MAN: "ssdp:discover"
MX: 3


12:24:29.408134 IP (tos 0x0, ttl 4, id 12491, offset 0, flags [none], proto UDP (17), length 157)
    192.168.122.191.62582 > 239.255.255.250.1900: [udp sum ok] UDP, length 129
..^...(.v0.N..E...0.....Z#..z......v.l....M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
MAN: "ssdp:discover"
MX: 3
```

----

With two NICs

```

sudo tcpdump -vv -A -s 0 -n 'port 1900 and host 239.255.255.250 and udp'
tcpdump: data link type PKTAP
tcpdump: listening on pktap, link-type PKTAP (Apple DLT_PKTAP), capture size 262144 bytes
12:19:54.500940 IP (tos 0x0, ttl 4, id 1710, offset 0, flags [none], proto UDP (17), length 157)
    192.168.122.191.53051 > 239.255.255.250.1900: [udp sum ok] UDP, length 129
..^...(.v0.N..E..........@..z......;.l..	.M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
MAN: "ssdp:discover"
MX: 3


12:19:54.742525 IP (tos 0x0, ttl 255, id 26770, offset 0, flags [none], proto UDP (17), length 156, bad cksum 0 (->ea93)!)
    172.19.204.28.64801 > 239.255.255.250.1900: [bad udp cksum 0x68c4 -> 0xd2b2!] UDP, length 128
..^...8..?y...E...h................!.l..h.M-SEARCH * HTTP/1.1
Host:239.255.255.250:1900
ST:urn:schemas-upnp-org:service:WANIPConnection:1
Man:"ssdp:discover"
MX:3

```

Notice it sends both with the first NIC address.

Client logs with two NICs
```
ssdp-client discovering all IPs from interface lo0 +0ms
  ssdp-client discovering all IPs from interface en0 +2ms
  ssdp-client discovering all IPs from interface en1 +0ms
  ssdp-client Will use interface en1 +0ms
  ssdp-client discovering all IPs from interface awdl0 +0ms
  ssdp-client discovering all IPs from interface utun0 +0ms
  ssdp-client discovering all IPs from interface utun1 +0ms
  ssdp-client discovering all IPs from interface utun2 +0ms
  ssdp-client discovering all IPs from interface utun3 +0ms
searching... sony
  ssdp-client SSDP listening: { address: 'http://0.0.0.0:53051', interface: '192.168.122.191' } +4ms
  ssdp-client Sending an M-SEARCH request +2ms
  ssdp-client Sent M-SEARCH request: { message: 'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-sony-com:service:ScalarWebAPI:1\r\nMAN: "ssdp:discover"\r\nMX: 3\r\n\r\n' } +1ms
  ssdp-client SSDP response: { message: 'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nEXT: \r\nLOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml\r\nSERVER: UPnP/1.0 MINT-X/1.8.1\r\nST: urn:schemas-sony-com:service:ScalarWebAPI:1\r\nUSN: uuid:000000001000-1010-8000-BAD7AF000148::urn:schemas-sony-com:service:ScalarWebAPI:1\r\n\r\n' } +2s
Got a response to an m-search:
200
{
  "CACHE-CONTROL": "max-age=1800",
  "EXT": "",
  "LOCATION": "http://192.168.122.1:61000/scalarwebapi_dd.xml",
  "SERVER": "UPnP/1.0 MINT-X/1.8.1",
  "ST": "urn:schemas-sony-com:service:ScalarWebAPI:1",
  "USN": "uuid:000000001000-1010-8000-BAD7AF000148::urn:schemas-sony-com:service:ScalarWebAPI:1"
}
{
  "address": "192.168.122.1",
  "family": "IPv4",
  "port": 42413,
  "size": 285
}
```

Packet dump with one NIC. Notice it sends using the correct from ip.
```
12:17:26.160293 IP (tos 0x0, ttl 4, id 31667, offset 0, flags [none], proto UDP (17), length 157)
    192.168.122.191.50678 > 239.255.255.250.1900: [udp sum ok] UDP, length 129
..^...(.v0.N..E...{......;..z........l...=M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
MAN: "ssdp:discover"
MX: 3
```

`192.168.122.191.50678 > 239.255.255.250.1900`


Client logs with one NIC
```
DEBUG=* node upnp/search.js
  ssdp-client discovering all IPs from interface lo0 +0ms
  ssdp-client discovering all IPs from interface en1 +1ms
  ssdp-client Will use interface en1 +0ms
  ssdp-client discovering all IPs from interface awdl0 +0ms
  ssdp-client discovering all IPs from interface utun0 +0ms
  ssdp-client discovering all IPs from interface utun1 +0ms
  ssdp-client discovering all IPs from interface utun2 +0ms
  ssdp-client discovering all IPs from interface utun3 +1ms
searching... sony
  ssdp-client SSDP listening: { address: 'http://0.0.0.0:50678', interface: '192.168.122.191' } +4ms
  ssdp-client Sending an M-SEARCH request +1ms
  ssdp-client Sent M-SEARCH request: { message: 'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-sony-com:service:ScalarWebAPI:1\r\nMAN: "ssdp:discover"\r\nMX: 3\r\n\r\n' } +1ms
  ssdp-client SSDP response: { message: 'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nEXT: \r\nLOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml\r\nSERVER: UPnP/1.0 MINT-X/1.8.1\r\nST: urn:schemas-sony-com:service:ScalarWebAPI:1\r\nUSN: uuid:000000001000-1010-8000-BAD7AF000148::urn:schemas-sony-com:service:ScalarWebAPI:1\r\n\r\n' } +2s
Got a response to an m-search:
200
{
  "CACHE-CONTROL": "max-age=1800",
  "EXT": "",
  "LOCATION": "http://192.168.122.1:61000/scalarwebapi_dd.xml",
  "SERVER": "UPnP/1.0 MINT-X/1.8.1",
  "ST": "urn:schemas-sony-com:service:ScalarWebAPI:1",
  "USN": "uuid:000000001000-1010-8000-BAD7AF000148::urn:schemas-sony-com:service:ScalarWebAPI:1"
}
{
  "address": "192.168.122.1",
  "family": "IPv4",
  "port": 42413,
  "size": 285
}
```

**Comment by LudekStoklasa** [comment]
I still see issues with multiple NICs support. The issue is that ip.address() returns the ip of the first interface only (when constructing the location URL).  So I had to modify the code and instead of supplying `location` param I supply just `locationPort` and `description` params so that the URL for "LOCATION" is created on demand for each corresponding interface, see my solution [here](https://github.com/mediamonkeyserver/mms/commit/4e8a67bb82fac95d1cf1d6cc6f718e151f3c78e7)

It would be good if you could push the changes into this original project so that everyone can benefit from it ;-)

**Comment by diversario** [comment]
@LudekStoklasa I've added that to v3.3.0, see `location` config option in the README. Thanks for pointing out the issue!

**Comment by diversario** [comment]
Seems like this issue's been addresses (or mostly addressed?..). I'm going to close it.
